{
 "title": "JTI-UDP-FPC-CPU-logstash",
 "tags": [
  "jti",
  "UDP",
  "logstash"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.cpu_memory_util_ext\" WITH KEY = \"device\""
   },
   {
    "name": "u_name",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.cpu_memory_util_ext\" WITH KEY = \"utilization.name\" WHERE \"device\" =~/$device/"
   },
   {
    "name": "app_name",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.cpu_memory_util_ext\" WITH KEY = \"utilization.application_utilization.name\" WHERE \"device\" =~ /$device/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU / Memory - frees per application (delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]--[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"utilization.application_utilization.frees\"), 1s) FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$device/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.application_utilization.name\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory Allocations per application (delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"utilization.application_utilization.allocations\"), 1s) FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$device/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory - Bytes allocated per application(delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]--[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"utilization.application_utilization.bytes_allocated\"), 1s)*8 FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$device/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory Bytes allocated Global - Kernel  (delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]--[[tag_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"utilization.bytes_allocated\"), 1s)*8 FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$device/ AND \"utilization.name\" =~ /^$u_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}